In [32]:
import requests_async
import os
import time
import pandas as pd

In [33]:
df = pd.read_csv('../datasets/all-repositories.csv')
df = df.assign(response_code = None, result_count = None)
df

                               name response_code result_count
0           001bug/springbootSource          None         None
1                       0n1cOn3/RRB          None         None
2                     0xCD0/retrofy          None         None
3     0xDev3/blockchain-api-service          None         None
4          0xPolycode/klaster-proxy          None         None
...                             ...           ...          ...
3824                 zvikfir/bullet          None         None
3825              zwvista/LollyJava          None         None
3826     zxcv9203/code-review-study          None         None
3827     zxygary/graduation-project          None         None
3828           zyf265600/Programmer          None         None

[3829 rows x 3 columns]

In [64]:
async def request(repository):
    return await requests_async.get(
        'https://api.github.com/search/code', 
        params = {'q': f"repo:{row['name']} language:java \"A class modelling foreign key relationships and constraints of tables\""}, 
        headers = {'Authorization': 'Bearer ' + os.getenv('GITHUB_TOKEN'), 'X-GitHub-Api-Version': '2022-11-28'}
    )

for index, row in df.iterrows():
    if row['response_code'] == None or row['response_code'] == 403:
        response = await request(row)
        df.loc[index, 'response_code'] = response.status_code
        df.loc[index, 'result_count'] = response.json()['total_count']
        print(row['name'], response.status_code, response.json()['total_count'])
        time.sleep(6.5)

sdeeg-pivotal/master-control-program 200 0
sdgdsffdsfff/bk-bcs-saas 200 0
sdsd0427/spring-boot-docker-app 200 0
sdumancic/quarkus-template 200 1
sealightsci/spring-boot-with-testng 200 0
sealuzh/cd-linter-artifacts 200 0
sebastian-raubach/frickl-web-server 200 1
sebastian-raubach/rpi-weather-server 200 0
sebastiendossot/grailsTests 200 0
sebivenlo/ESD_Spring_framework_2022 200 0
second-constantine/hello-jvm 200 0
secs-dev/itmo-dating 200 0
seculoper235/infra-file-service 200 0
seed4j/seed4j 200 0
seetadev/WaterMonitor 200 1
self-xdsd/self-storage 200 1
senior-cyber/frmk-master 200 0
seokho-1116/community-api 200 0
serdeliverance/turro-lingo-api 200 1
serefarikan/travis-test 200 0
sergey-kulak/acme-system 200 0
sergioperdomo/E-commerce 200 0
serhiomatviavelli/SocialNet 200 0
serhiomatviavelli/TicketOffice 200 0
serje3/BotDiscordBackend 200 1
serviceprototypinglab/sentinel 200 0
sevvalnr/1000KInitial 200 0
sfk25/annually_report 200 1
sge93/jooq-testcontainers-demo 200 1
sgrimm/jooq-kotlin-2-example 200 0
shahdewang/tinyurl 200 0
shahlin/reef 200 0
shajith-dev/Notehub-Spring-Boot 200 0
shankar7979/java_2024 200 0
shanmugs/misc_progs 200 0
shaorooney/maven 200 0
shaposhnyk/graphql-jooq 200 0
shchepelevnikita/7quizzes 200 0
shengquan-ni/reshape-on-amber 200 2
shenzepeng/media-center 200 0
shev-81/jooqtest 200 1
sheva3666/dictionary-api 200 0
shileishmily/spring-boot-jooq-demo 200 1
shilohooo/learn-jooq 200 3
shin6142/attendance_app_v2 200 0
shiori0803/demo 200 0
shivam75/JenkinsAssessment 200 0
shixiaoliuo/general-utility-demo 200 0
shobhitj34/NRM-test 200 0
shoheyheyhey/poc-spring-vue3-keycloak 200 0
shoheyheyhey/software-design-practice 200 0
shotaod/carbon 200 0
showwin/ISUCON5 200 0
shrav2007/test-myktor-project 200 0
shulieTech/Takin-surge-deploy 200 0
shumy-tools/fatcoach 200 0
shuvo1533/tempCamel 200 0
shydesky/tutorials 200 1
sify21/testjooq 200 1
sikt-no/graphitron 200 1
silencily/spring-ai-lab 200 0
silentbalanceyh/r2mo-rapid 200 0
silentbalanceyh/rachel-momo 200 0
silentbalanceyh/vertx-zero 200 14
silentbalanceyh/vertx-zero-0.6 200 9
siliang0426/StudentsManagement 200 0
sim1984/fbjavaex 200 1
simasch/cqrs-meets-modern-java 200 0
simasch/crud 200 0
simasch/jooq-examples 200 0
simasch/kutu-tipp 200 0
simasch/orders 200 0
simasch/spring-io-2022-vaadin 200 0
simondongji/SpringCloudProject 200 0
simonwang544/college-cuhksz- 200 0
simplecloudapp/player-droplet 200 0
sipe-team/3-1_spurt 200 0
sivaprasadreddy/beginning-spring-boot-2 200 1
sizo0/BDAProject 200 0
sjiwon/Advanced-Another-Art 200 0
sjiwon/devlog-codes 200 0
sjucker/mvu-platform 200 1
sjucker/referee-coach-probasket 200 1
sjucker/zkmf2024-server 200 1
skapral/poetryclub 200 1
skberkeley/bmun_invoicing 200 0
skfl/rostovskii-sound-cloud 200 0
skhahamyan/bblarmenia 200 0
skyleedevzero86/Spring_lee_Module 200 1
skyrocknroll/jooq-test 200 0
slaveuser/spring-boot20180215 200 0
sleaf-dev/DarkWaterAPI 200 0
sleaf-dev/MineCore 200 0
sleeg00/just 200 0
slopwell/sandbox 200 0
slyisarenko-ilya/ExcelImporter 200 0
sm2774us/everything_finance_and_tech 200 0
smac89/robotsjavabackend 200 0
smagellan/misc-experiments 200 0
smartywebdev0119/springsecurity-top 200 1
smix22/kitaplan 200 1
smix22/wochenplan 200 1
smockoro/okutama 200 1
smockoro/spring-boot-java-jooq 200 1
smth-to-smb/Project-name 200 0
snhr-1019/task-app-example 200 1
snyk/cli 200 0
sofimari09/java-project-copy 200 0
sogeking7/booking-hotel-app 200 1
sogeking7/hacknu-25-zaman-bank-ai-app 200 1
sokolovskayaa/tinkoff-project 200 1
solankydev/jooqdemo 200 0
solven-eu/adhoc 200 0
solven-eu/pepper 200 0
somayya-9/docker-docker-compose-docker-swarm 200 0
somebodysomebodynov/muse-project 200 0
sonicle-webtop/webtop-core 200 0
sonicle-webtop/webtop-superpom-service 200 0
soon83/SpringModuleX 200 0
sooogle/micronaut-petclinic 200 1
soranico/letter-song-spring-boot 200 0
sosuisen/bmi-mvvm-with-builder 200 1
sotterbeck/iu-metro 200 0
sounfury/sounfury-blog 200 0
sourcecase/jooq-with-docker 200 0
sowmya1022/CTS_Superset_5019401 200 0
spacedragon/dgit 200 1
spark-teams/jootainer 200 0
spazzylemons/DogCore 200 0
spectuu/equipo-4-ings-202520 200 1
spember/eventsource-ratpack-reference 200 0
spember/jooq-demo 200 0
spember/spring-bikeshed 200 0
speranzaaa/DB-Project 200 1
spexity/spexity 200 0
spinnaker-cn/orca 200 0
spinnaker/spinnaker 200 0
spotfinder-project/backend 200 0
spoud/kafka-cost-control 200 0
spring-gradle-plugins/spring-build-conventions 200 0
spring-petclinic/spring-petclinic-jooq 200 0
spring-projects/spring-boot 200 0
spring-projects/spring-data-examples 200 0
spring-tips/jooq 200 0
springboot-angular2-tutorial/boot-app 200 0
springmonster/multi-tenancy 200 0
spullen/reactive-todos 200 0
srcclr/sapling 200 1
srijan-96/FlightReservationSystem 200 0
sscarduzio/elasticsearch-readonlyrest-plugin 200 0
ssomai/MyJavaLibrariesWithJitPack 200 0
ssricoolgirl/DatabaseUpdationUsingSpring 200 0
ssspamqe/Link-Tracker 200 0
ssullivan/aws-transcribe-poll 200 0
ssullivan/mta-bus-tracking 200 0
ssullivan/treatmentcenter-api 200 0
ssydx/django_wesite 200 1
stantonk/jooq-sandbox 200 0
stefan-cross/whitelabel-kotlin-service 200 0
stella6767/spring-scratcher 200 0
stellarnexus2018/spring-level 200 0
stemlaur/anki 200 0
steve-community/steve 200 0
steveyangpi/pro-spring-6-Learning 200 2
stikhovs/memo-app 200 0
stillya/grpc-spring-starter-bug 200 0
stosik/cockroach-r2dbc 200 0
stpasha/financeapp 200 0
stppy/tcp 200 0
strawberrylin/Hust_Cs_ComplierOl 200 0
streamarr/streamarr-server 200 1
strindberg/jooq-issue-11165 200 0
studio-styx/erisbot-java 200 0
stukenvitalii/TinkoffBot 200 1
subin-Jeong/aplus-batch-auth 200 0
sumaiyalamgir/CleanIt 200 0
sun-fintrack/fintrack-back 200 1
sungmin-park/kotlin-jooq-test 200 0
surecloud-hcrispin/mini-aurora 200 0
svp8/java-course-2024 200 1
swaechter/fhnw-wodss 200 0
swaechter/jooq-gradle-testcontainer-flyway-example 200 0
sweatboys/open-discogs-api 200 1
swerchansky/tinkoff-java 200 0
swordess/vitool 200 0
swucs/jooq-test-maven 200 0
sychevskayaPI12/lms-user-service 200 0
syliGaye/tutorials 200 1
sylvaindecout/jooq-handson 200 0
sylvaindecout/pumpkin-spice-latte 200 0
sylvan-tang/auro 200 1
synonymdev/vss-server 200 1
t-suguru/book-management 200 0
t3hw/mhn 200 1
t9t/jooq-postgresql-json 200 0
tadashi1105/book-api 200 0
tadfisher/gradle2nix 200 0
tahir-mehmood/killbill-easytax-plugin 200 0
tailrocks/tailrocks-domain-template 200 0
tain198127/GithubHawkEye 200 0
taion809/humans 200 0
taiprovip3/KTTKPM_ShopPlant 200 0
tak2siva/SpiCinemasAPI-TeamA 200 0
takari/ollie 200 0
takumi2003/springboot-jooq-docker 200 0
tamas2792/test-automation-framework-selenide 200 0
tamas2792/test-automation-selenium-grid 200 0
tanish1409/SOFE3980-Lab3 200 0
tanjezh/spring-demos 200 3
taozhe1/maven3.6.3_repository 200 0
tapis-project/tapis-apps 200 1
tapis-project/tapis-bom 200 0
tapis-project/tapis-files 200 1
tapis-project/tapis-meta-bom 200 0
tapis-project/tapis-notifications 200 1
tapis-project/tapis-systems 200 1
tariqkb/dropwizard-jooq 200 0
tariqkb/justweighit 200 1
tatsuki-52/portfolio_dev 200 0
taxilang/taxilang 200 0
team-tsukuba/isucon5q-test-all 200 0
tech-by-design/polyglot-prime 200 0
techblue/cgh-processor 200 0
techyNouman/spring-jooq 200 0
tedburner/spring-boot-examples 200 0
teichholz/chat-server-kt 200 1
tejozarkar/JooqSpringBootPostgreSQLDemo 200 0
telecomstackjp/kestra 200 0
telekom/nuSIM-Loader-Application 200 0
tengshe789/SpringCloud-miaosha 200 0
teragrep/cfe_41 200 0
teragrep/pth_06 200 3
terraware/terraware-server 200 0
teruiV/SpringBootDemo 200 0
testcontainers/testcontainers-jooq-codegen-maven-plugin 200 0
tgrez/sejm-ngram 200 0
th3n3rd/http4k-playground 200 0
thanesh56/productcatalog 200 0
the-prairie/source-alberta-re 200 0
the-programmers-hangout/Mimic 200 1
theSiriusDebug/MovieService 200 0
thedatasnok/spring-jooq 200 0
thedimasNetwork/DatabaseWrapper 200 1
thedimasNetwork/StellarPlugin 200 0
therepanic/hr-masters-service 200 1
therepanic/jooq-reactive-gradle-test 200 0
therepanic/lapayment-crypto-pay-system 200 1
therepanic/lapayment-crypto-payment-system-microservices 200 5
therepanic/micronaut-jooq-flyway-example 200 0
therepanic/trustwin-casino-project 200 7
theronielanddaronpodcastshow/svja 200 1
thiago-buarqque/backend-java 200 0
thingersoft/maven-repo 200 0
thinkingGorilla/learning_jooq 200 0
thomas15v/MapLog 200 0
thomas15v/breakout-groep23 200 0
thomascherickal/hedera-stable-coin 200 1
thomasm1/app-kafka-elasticsearch-tweets 200 0
thomasm1/java-web-cli 200 0
thombergs/components-example 200 0
thushear/doit 200 0
tian-junwei/zipkin-storage-postgresql 200 0
tianyijushi/spring-boot 200 0
tim-mortimer/habitpal 200 0
timing1337/mineplex-reborn 200 0
timofeev-denis/examples 200 0
timotuunanen/ktor-template 200 0
tinywind/BABEL-CODEGEN 200 0
tinywind/SCHEME-REPORTER 200 0
tinywind/SPRING-I18N-CONVERTER 200 0
tinywind/react-spring-messenger-server 200 0
tiongg/cs102-proj 200 0
tjdragon/tjcbs 200 1
tjpark312/JPA_Study 200 0
tkykymok/ddd-demo 200 0
tkykymok/qms-server 200 0
tkykymok/root-project 200 0
tmanas06/g2210030003 200 0
tmtbe/springboot-scaffold 200 0
tmtsoftware/aps-procedure-read-benchmarking 200 1
toannv6895/searchable 200 1
today8934/jOOQ-first-look 200 1
toefel18/ig-stock-service 200 0
tokkaiiii/jOOQ-practice 200 0
tokkaiiii/tokkaiiii-bugs 200 0
tokumura/librarian 200 0
tomdcc/miniprofiler-jvm-jooq-example 200 0
tomoncle/tomoncle.github.io 200 0
tonyfieit/springbootcrudrepositorydemo 200 0
tonykolomeytsev/in-your-pants-bot 200 0
topcoder-platform/informix-access-layer 200 0
torgammelgard/jooq-demo 200 0
torgge/spring-angularjs-datapar 200 0
torodb/build-tools 200 0
torodb/engine 200 0
torodb/testing-tools 200 0
total66/alibaba-faw-source 200 0
toxicafunk/mdd 200 0
tracksdata/CTS-Spring-Boot 200 0
traffic-hunter/traffic_hunter 200 0
trashds194/RostovBusAlertBot 200 0
treetips/kotlin-spring-boot-jooq-liquibase-thymeleaf-example 200 1
treetips/kotlin-spring-boot-webflux-springfox-example 200 1
treetips/spring-boot-flyway-jooq-example 200 0
trib3/example-cauldron-service 200 0
trib3/leakycauldron 200 0
trivedii/library-management-api 200 0
truonghq99/adam-project 200 1
trxplorer/explorer 200 0
trydofor/professional-wings 200 0
tschuehly/hyperspring-demo 200 0
tseebilguun/promo-a25-058-ny 200 0
tseebilguun/promo-toki-mobile-ny-2025 200 0
tsemkaloalena-mirea/vk_education 200 3
tsoyolv/transfer-money 200 1
tssvett/JLain 200 0
tssvett/T-Invest-Tracker 200 0
ttomasicc/ai-melodies 200 1
tutibase/MovieRecommendationBot 200 0
tuyucheng7/taketoday-tutorial4j-backup 200 3
tuyucheng777/taketoday-tutorial4j 200 3
tvidal-net/tvidal-lib 200 0
tw-bc-group/tw-wallet-backend 200 2
tylerbenson/vyllage 200 0
tyomamatrosov/MatrosovAS 200 1
typsoon/ID-project 200 0
typsoon/MTGspot-scrapper 200 0
typst-io/bukkit-kotlin-plugin 200 0
typst-io/spigradle 200 0
typst-io/virtual-chest 200 2
u-verma/springboot-jooq-flyway-Integrationtest 200 0
u-ways/spring-boot-reactive-microservice-kt 200 0
ucsdlib/bridge-restore 200 0
uianz/webflux-jooq-r2dbc-starter 200 1
ultish/jooq-test 200 0
ultrapotato69/genealogy-back 200 1
umi-ushi/quo-shelf 200 1
umi-ushi/spb-dev-kit 200 0
umuo/spring-boot-2-2-9-release 200 0
unipop-graph/unipop 200 0
unlessiamwrong/Tinkoff-Java-course-2 200 1
unlimitedcombor/Travel 200 0
uol-esis/Th1nk 200 0
uptosmth/chronos 200 1
ureca9/BE_MungGu 200 0
user-register-app/reader-api 200 0
usmanzaheer1995/spring-boot-demo 200 0
usmanzaheer1995/spring-boot-security 200 0
utfunderscore/buildformat 200 1
utwente/sketchlab 200 0
uvuv-643/Service_Oriented_Architecture 200 4
vaadin/whereabouts 200 0
vaclavskorpil/assignment-transactions 200 0
valeriuvancea/orm-example 200 0
valitydev/analytics 200 0
valitydev/disputes-api 200 0
valitydev/disputes-tg-bot 200 0
valitydev/dominator 200 0
valitydev/fraudbusters-notificator 200 0
valitydev/gambit 200 0
valitydev/liminator 200 0
valitydev/rate-boss 200 0
valitydev/repairer 200 0
valitydev/reporter 200 0
valitydev/vortigon 200 0
valitydev/wallets-hooker 200 0
vamshisoma9/name 200 0
vankadararaghav/AirLine-Reservation-System 200 0
vaseem999/haslee 200 0
vaskocuturilo/amazon 200 0
vbandurin7/update-listener-bot 200 1
vendelieu/spring-template 200 1
vertabelo-modeler/vertabelo-jooq 200 0
viartemev/ktor-jooq 200 1
vibhor-pandey/spring-boot-boilerplate 200 0
victorursan/banana 200 0
vigor-yuan/steve 200 0
vikaschenny/rewrite-spring 200 0
vikashbasant/spring-boot 200 0
vimc/montagu-system 200 1
vimc/orderly-web 200 1
vinniec4/fantasy-football 200 1
vinodaravind01/polyglot-prime-test 200 0
vishalhemvi/demo-1 200 0
vishalkrishnaagQwy/VipLang 200 0
visualkhh/lib-spring 200 0
vityaman-edu/lms 200 0
vityaman-edu/web-taparia-jakarta 200 0
vivekkothari/game-leaderboard 200 0
vkuzel/Orm-Frameworks-Demo 200 0
vkuzel/Quantum-Leap 200 1
vladigeras/spring-jooq-k8s 200 0
vladislav77777/java-backend-course 200 1
vladkanash/r2dbc-jooq-demo 200 0
vladmihalcea/high-performance-java-persistence 200 0
vladmihalcea/high-performance-jooq 200 0
vmware-archive/differential-datalog 200 0
voidframework/voidframework 200 1
volvas/courses 200 1
vonlinee/code-examples 200 0
vonox7/spring-jooq-experiments 200 0
vonzhou/spring-boot-notes 200 0
vorpal-research/kotoed 200 0
votabulary/Trainer 200 0
vpaladino778/sweep-backend 200 0
vran-dev/databasir 200 1
vrrs/cyclop 200 0
vsfedorenko/gradle-require-docker-plugin 200 0
vuorimaav/backend-demo 200 0
vursen/tree-grid-example 200 0
vusalahasanova01/AuthProject 200 0
vusalahasanova01/grpcTask 200 0
vusalahasanova01/security 200 0
vusalahasanova01/usingGrpc 200 0
vzurauskas/accounts-transfers 200 0
w-k-s/Service-Marketplace 200 0
w-k-s/Terraform-Experiment 200 0
w350491385/serverApi 200 0
waddadelmehdi/configuring-connecting-cloud-sql 200 0
waddadelmehdi/integrating-pub-sub-with-spring 200 0
waddadelmehdi/integrating-pub-sub-with-spring-outboundGateway 200 0
waddadelmehdi/uploading-and-storing-files 200 0
wafflestudio/csereal-script 200 0
waikato-datamining/adams-discontinued 200 0
walissonssousa/Start-java-Oracle-Docker 200 0
wallrat/spring-boot-app-using-gradle 200 0
wallstreetcn/nortrom 200 0
walmartlabs/concord 200 0
wandu98/ITWILL 200 0
wang-yan-github/qd-zhtc 200 0
wangshibiaoFlytiger/springmvc 200 0
wangyingchu/docg_platform 200 0
warhog/fpvlaptracker 200 1
warumono-for-develop/spring-boot-jooq-tutorial 200 0
wasim-essbai/unibg-tutorato-ing-sw-2324 200 0
watisluv1910/vlantegrator 200 0
waydxd/COMP3111-Project 200 1
wb02125055/spring-boot-2.1.x-source 200 0
wbprime/java-mods 200 2
wcygan/quarkus-server-template 200 0
wcygan/quarkus-temporal-example 200 0
we-huddle/server 200 1
web3brothers/aleo-network-info 200 1
weery28/vjooqx 200 0
wfuertes/playlist_netflix_stack 200 0
whizvox/wsite 200 1
whwp4151/spring-boot-jooq-sample 200 0
whxu215/jooq-springboot-example-junit 200 1
williiam-tran/Health-First 200 0
willmitchell/jooq-jhipster-generator 200 0
willmitchell/sample-jooq-model-with-access-control-and-orders 200 0
wing1016/springboot 200 0
winwinsolution2025/auth-service 200 0
with-git/spring-boot 200 0
wojesen/springboot 200 0
wolfiabot/Wolfia 200 0
wolfs/bt-dev-prod-data-collector 200 1
wombat-tech/backend-spring-coding-challenge 200 0
wonjunJ/Fluffit 200 1
woozi-playground/jooq-playground 200 0
wq352400523/hadoop-study 200 0
wqcsimple/java-api-base 200 0
wqcsimple/java-file-preview 200 0
wsawa-q/evaluation-of-db-performance 200 0
wsmaking/event-switchyard 200 0
wu123tao/wps-weboffice-v3-demo 200 0
wuda0112/foundation 200 6
wudgaby/wudgaby-platform 200 0
wuhunyu/jooq-transaction 200 1
wujihulian/filesbox 200 2
wuruiliang/xwlbAnalysiser 200 0
wwwyssa/wwwyssa_in_itmo 200 0
wyntjpu2023/shardingsphere 200 0
wzjgo/loan 200 0
wzjgo/transfer 200 0
x90613/Team_Buying 200 0
xGodness/service-oriented-architecture 200 1
xJade00/TavernMaid 200 1
xala3pa/spock-workshop 200 0
xdnw/Diplocutus 200 5
xdnw/locutus 200 5
xenit-eu/contentgrid-appserver 200 0
xiangxik/castle-cloud 200 0
xiezw96/pig 200 0
xingmin1/video-spring 200 1
xinxiamu/mu-spring-boot-sample 200 1
xiz675/AWESOME-new-version 200 0
xnelo/filearch 200 1
xnull/rent4me 200 0
xp-zhao/learn-java 200 0
xstefank/kotlin-quarkus 200 0
xuminwlt/j360-trace 200 0
yamachoo/ktknowledge-todo 200 0
yan6/swiftbuy 200 0
yang-717/Recruitment-of-Data-Visualization-Analysis-System 200 0
yangga/kopring-restapi-boilerplate 200 0
yanggy9501/spring-boot-source 200 0
yangjinguang/i-share-server 200 1
yank-machado/spring-commerce-platform 200 0
yaowei-u/kafka 200 1
yaseenkadir/etchedjournal 200 1
yash170106065/indigo 200 0
yasha-dev1/windsurf-tdd-showcase 200 0
yashdesai023/HireSense-AI 200 0
yashh152004/Spring-reset 200 0
yasin904/Parking-Lot-Api 200 0
yassineyassine/erp-microservices-fullstack-java-cicd 200 0
ydb-platform/ydb-java-dialects 200 1
ydb-platform/ydb-java-examples 200 1
ydeng11/Minance 200 1
yegor-usoltsev/noom-sleep-logger 200 0
yeikel/dependabot-limit-tests 200 0
yesworkflow-org/yw-prototypes 200 0
yewton/petclinic 200 0
yeyeongkwak/book_rental_application 200 0
yfs666/routine 200 0
yichunzhao/jooq-dao 200 1
yigitbalcioglu/End-to-End-Data-Engineering 200 0
yihaozhong/BuyUp 200 1
yildiz-online/module-database-mapping-jooq 200 0
yilmazorhan/smallapps.tips 200 1
yiminyangguang520/Java-Learning 200 1
yin5980280/easy 200 0
ymind/rsql 200 0
ymosinzon/BMPhysio 200 0
ymzksgkz/books-search 200 0
yogurt-dev/yogurt 200 0
yohei-ino/LibraTrack 200 0
yonatankarp/cat-fact-service 200 0
yonatankarp/spring-starter 200 0
yoshiki-0428/BizToi 200 0
yoshipi/booksManage 200 0
young0264/jungsuri 200 1
youngAndMad/spring 200 0
youngzil/quickstart-database 200 2
youssef-baroudi/java-spring-boot-api-mysql 200 0
youth-k110/jooq-flyway-sample 200 0
ysden123/poc 200 0
ysjiang4869/code-example 200 0
ysjiang4869/pom-starters 200 0
yuanmabiji/spring-boot-2.1.0.RELEASE 200 0
yuanssai/quarkus-template 200 0
yuizho/jooq_sandbox 200 1
yuizho/spring-sandbox 200 1
yukihane/hello-java 200 0
yuqi1129/schema 200 0
yusuiked/daguerreo 200 0
yusuiked/jooq-sample 200 0
yuu-nkjm/sorm4j 200 0
yuwestboy/traffic-master 200 0
yuzhongyousida/zipkin 200 1
yvbro/ReXA 200 1
yvovc/p2pmediator 200 0
yxc023/code-examples 200 0
yyh-gl/hobigon-user-box 200 0
yzystart/spring-boot-2.2.5.RELEASE 200 0
zaki-x86/fintech-microservices 200 0
zangzang/java-test 200 1
zanxiaofeng/zxf-java-maven-project 200 0
zarebski-m/jooq-codegen-repro 200 0
zeitwert/fm-server 200 12
zengqignjiong/yuezican 200 0
zephyr7419/pms 200 1
zepinto/jooq-test 200 0
zero-ws/zero-ecotope 200 14
zero-ws/zero-energy 200 0
zeyadahmed10/Java-Query-Performance-Benchmark 200 0
zhangjun075/brave-jooq-sample 200 0
zhangqinjava/mall-skill 200 0
zhangyang-dev-engineer/springboot-2.6.6 200 0
zhaoshengj/spring-boot-2.2.x 200 0
zhaoshouren/spring-boot-pom-for-caching 200 0
zhengframework/zhengframework 200 0
zhengqingya/java-workspace 200 1
zhengzizhe/agent_demo 200 1
zhenmYan/development-tool-kit 200 0
zhou999848/job-tracker-saas 200 0
zhoupan/jooq-android 200 13
zhouzhaodong/springboot 200 1
zhuyb0614/graph-batis 200 1
zigzag191/java-backend-course-2024 200 1
zjxkenshine/codedemo 200 1
zodac-personal/folding-stats 200 1
zonaut/spring-boot-reactive-playground 200 0
zphrio/jooq-with-htmx-todos 200 0
zubairmujeeb/spring-boot-sample-projects 200 1
zvikfir/bullet 200 0
zwvista/LollyJava 200 0
zxcv9203/code-review-study 200 0
zxygary/graduation-project 200 0
zyf265600/Programmer 200 0

In [67]:
print(df['response_code'].value_counts())
print(df['result_count'].value_counts())
df

response_code
200    3829
Name: count, dtype: int64
result_count
0     3027
1      689
2       60
3       19
5        6
4        5
6        4
7        4
12       3
11       2
14       2
17       2
15       1
8        1
20       1
10       1
9        1
13       1
Name: count, dtype: int64

                               name response_code result_count
0           001bug/springbootSource           200            0
1                       0n1cOn3/RRB           200            0
2                     0xCD0/retrofy           200            0
3     0xDev3/blockchain-api-service           200            0
4          0xPolycode/klaster-proxy           200            0
...                             ...           ...          ...
3824                 zvikfir/bullet           200            0
3825              zwvista/LollyJava           200            0
3826     zxcv9203/code-review-study           200            0
3827     zxygary/graduation-project           200            0
3828           zyf265600/Programmer           200            0

[3829 rows x 3 columns]

In [68]:
df_valid = df[df['result_count'] > 0]
df_valid

,name,response_code,result_count
20,2023-ict-itmo-city-project/city-project-backen...,200,1
26,320Hwany/jOOQ-Study,200,1
28,4el1k/Spring-Api-Hibernate-JOOQ,200,1
29,51568488/vertx-zero,200,1
33,66xc1/lazy-punch,200,1
...,...,...,...
3817,zhuyb0614/graph-batis,200,1
3818,zigzag191/java-backend-course-2024,200,1
3819,zjxkenshine/codedemo,200,1
3820,zodac-personal/folding-stats,200,1
3823,zubairmujeeb/spring-boot-sample-projects,200,1

In [69]:
df_valid.to_csv('../datasets/repositories-with-generated-classes.csv', index=False)