In [7]:
import requests_async
import os
import time
import pandas as pd

In [8]:
df = pd.read_csv('../datasets/repositories-with-generated-classes.csv')
df = df.assign(response_code2 = None, result_count2 = None)
df

,name,response_code,result_count,response_code2,result_count2
0,2023-ict-itmo-city-project/city-project-backen...,200,1,None,None
1,320Hwany/jOOQ-Study,200,1,None,None
2,4el1k/Spring-Api-Hibernate-JOOQ,200,1,None,None
3,51568488/vertx-zero,200,1,None,None
4,66xc1/lazy-punch,200,1,None,None
...,...,...,...,...,...
797,zhuyb0614/graph-batis,200,1,None,None
798,zigzag191/java-backend-course-2024,200,1,None,None
799,zjxkenshine/codedemo,200,1,None,None
800,zodac-personal/folding-stats,200,1,None,None
801,zubairmujeeb/spring-boot-sample-projects,200,1,None,None

In [9]:
async def request(repository):
    return await requests_async.get(
        'https://api.github.com/search/code', 
        params = {'q': f"repo:{row['name']} language:java \"import org.jooq.DSLContext\""}, 
        headers = {'Authorization': 'Bearer ' + os.getenv('GITHUB_TOKEN'), 'X-GitHub-Api-Version': '2022-11-28'}
    )

for index, row in df.iterrows():
    if row['response_code2'] == None or row['response_code2'] == 403:
        response = await request(row)
        df.loc[index, 'response_code2'] = response.status_code
        df.loc[index, 'result_count2'] = response.json()['total_count']
        print(row['name'], response.status_code, response.json()['total_count'])
        time.sleep(6.5)

2023-ict-itmo-city-project/city-project-backend-core 200 0
320Hwany/jOOQ-Study 200 0
4el1k/Spring-Api-Hibernate-JOOQ 200 5
51568488/vertx-zero 200 1
66xc1/lazy-punch 200 5
ABCLV/ABLV_IngSW 200 1
APSfurizon/fz-backend 200 3
AWS-Cloud-Community-LPU/mailing-service 200 1
AffectedArc07/ParaUtil 200 1
AisleiAvila/empresa 200 7
AkaLrz/E-commercial-Platfrom 200 5
AlekseySamoylov/jooq 200 0
AlekseySamoylov/transaction 200 0
AlexSpeal/Tracking-Bot 200 3
Alexandr-Kokorin/JavaCourse2024 200 3
AlexzTj/p2p 200 2
AlphaFoxz/oneboot 200 2
AnastasiaPleshkova/tnkf-tracker 200 2
AndrewSalygin/LinkTracker-Tinkoff 200 3
Andrey582/NotificationBot 200 3
Ani512/online-tutoring-app-backend 200 5
AntonioRusan/LinkTracker 200 5
Apress/beginning-jooq 200 30
Apress/pro-spring-6 200 4
Apress/pro-spring-6-kotlin 200 0
AprilHan1992/fleet-spring-boot 200 1
ArcaHozota/nasb1995edv3 200 4
Arden30/TinkoffJavaBackendSpring23-24 200 4
AtroposBot/Atropos 200 1
Atsushi68/trunk 200 2
Ayazkins/Java-Tinkoff-sem-2 200 4
BRP-API/brp-api-gezag 200 2
BenMAPCE/BenCloudServer 200 24
Beyond-Article1/MediHub-BE 200 0
BinaryIgor/tools-and-templates 200 10
Blackdread/rest-filter 200 1
BlakieSL/SpringJOOQ_DAO 200 2
BluBluBlaBla/vidsummize 200 1
BogBond2000/Itmo_labs 200 3
BorisovAlexspb/Update_tracker_bot 200 8
Bruh3509/updates-tracker 200 4
BuchnevDmitry/LinkTracker 200 3
BudgetingWebsite/Backend 200 8
CaXaPCMeDoM/tinkoff-java-course-2024-backend 200 6
CaptainCluster/data_intensive_assignment_3 200 1
CatOrLeader/Tinkoff_Link_Tracker 200 3
CellarHQ/cellarhq.com 200 0
ChatCode9/ChatCode-backend 200 11
Claydelas/dashboard-fx 200 1
D-Muscipula/tinkoff-java-backend-link-tracker-project 200 4
DanieleGotti/MED 200 39
Daniil-Vl/link-tracker 200 6
Daniil4639/Tinkoff_Repository_2 200 3
DanjiTalk/danji-talk-backend 200 3
Dankoy/jforwarder 200 2
DarplexDev/darplex-java 200 1
DavidJi80/springboot 200 1
Davincii254/Stroom 200 17
Daza10samu/booksourcing 200 0
DiSSCo/dissco-core-annotation-processing-service 200 5
DiSSCo/dissco-core-backend 200 7
DiSSCo/dissco-core-digital-specimen-processor 200 3
DiSSCo/dissco-core-translator 200 5
DiSSCo/dissco-data-exporter-backend 200 3
DiamondArt/Java-jooq 200 2
DmitriyKosolobov/java-course-2024-backend 200 4
DrBrother/notification-system 200 4
DragomiroiuStefan/rideshare 200 6
Drewbie18/spring-rest 200 3
E1psycongr00/STUDY_REFERENCE 200 2
E1psycongr00/study_jooq_codegen_with_flyway_jpa 200 2
EGO-R/alexandrina 200 0
EGO-R/backend 200 0
EHRoute/EHR-Route 200 1
Efler/microservice-data-bus 200 7
Efler/telegram-scrapper-bot 200 4
Eliorika/tinkoff-java-backend 200 5
Emented/webLab3 200 1
EngineDevOps2/programming-todolist-fullstack 200 1
EuphoriaV/UpdateMonitoringBot 200 4
FOKO-KENMOGNE-Wilfried/siggeac_prototype 200 3
FeKom/lab-ecommerce 200 1
FeldmannJR/constellation-common 200 4
FeldmannJR/redstonegang 200 2
FiMDiscord/fimcraft-plugin 200 0
Fics3/tink_java_backend_course_spring 200 8
FilippoBolis/MED_Progetto_Ing_Software_23_24 200 24
Flexicon/message-wall-kt 200 0
FrankChen021/bithon 200 41
FrankChen021/bithon-demo 200 1
Fxsh-pro/core-crm 200 0
Fxsh-pro/reels_stories_download_tg 200 0
Fxsh-pro/vk_queue_bot 200 0
GAIM-Tech-OM/killbill-ompay-plugin 200 1
Gabriele-Mazzoleni/SmarTrip 200 3
Garrettc96/cacophony 200 8
Geomatys/examind-community 200 2
GeorgyDemidenkov/DemidenkovGD_Y-234_2kurs2sem 200 2
Gmugra/net.cactusthorn.micro 200 0
Grigalgol/vk_education_hm6 200 4
Grigalgol/vk_education_hm7 200 0
GyrosOfWar/imagehive 200 7
HSLdevcom/jore4-jore3-importer 200 37
HSLdevcom/jore4-map-matching 200 0
Hamednallah/Basariat-POS 200 26
Hamednallah/Market-POS 200 11
Hellblazer/quantum-db 200 2
Hixon10/spring-boot-security 200 1
HoZanDung/ho-workflow 200 19
Hogeyama/try-java 200 2
Hyunk3l/kotlin-orms 200 0
IAGrig/link-updates-notifier 200 3
INSide-734/MythicAchievements 200 0
IlyaAbramovv/UpdatesAnnouncer 200 3
Impolex/Office_Archive 200 0
IvanShabunin379/java-course-2024 200 3
JGMelon22/ListDemoJava 200 1
JacobLewandowskiDev/GwentMMO-Backend 200 1
JakeMathews/recommendation-engine 200 3
JarHax/TGATAGACTTAGTGA 200 0
JixinZhang19/Online-Shopping-System-for-Black-Friday 200 8
JohannesRabauer/hibernate-vs-jooq 200 3
Jominjong/mjjo-test-project 200 3
KEN3pei/oauth-hands-on 200 6
KGjertsson/macro-hub 200 12
Karthik1226/onedata_patient 200 5
Kazuuma-19/nippogen 200 4
KevinOCM99/tutorials 200 6
Kirill06344/TinkoffWebApplication 200 4
KirillSakira/link-tracker 200 4
KittyBot-Org/KittyBot 200 1
Knicksaas/gourmet-gate 200 11
KyleGuanDP/Assignment4 200 2
LARCH1K/LinkTracker-Bot 200 3
LaDfBC/Gloomhaven_DeckTracker 200 0
LalisaST/java_course_2 200 3
LeHa2505/OnThiService 200 23
LiangChenDLJ/VIPManager 200 8
LianjiaTech/bella-assistants 200 12
LianjiaTech/bella-knowledge 200 6
LianjiaTech/bella-openapi 200 10
LianjiaTech/bella-workflow 200 8
Link-Profit-System/java_mvvm 200 2
LintaoAmons/java-jooq-runable-code 200 4
LogDS/SimulatorOrchestrator 200 48
LucidMinded/java-course-2023-backend 200 7
M1nsong-Kim/practice-jooq 200 2
MAK-Cpp/backend-java-s2 200 4
MIZINCHIK/java-course-2023-backend 200 5
Macbeth-Klm/Tinkoff-java-course-2024 200 4
Maczi01/sockets 200 5
MahjongRepository/YagiMotel 200 1
Malest-GmbH-Co-KG/Prog_3_Projektarbeit 200 9
ManoManoTech/hexa-playground 200 0
MarinaBiryukova/tinkoff-java 200 4
MaroderKo/parts_shop 200 1
Mateuzz/music-website-spring 200 1
MaxZhukoff/tinkoff-bot 200 2
Missssha/Tinkofff-Back 200 2
Molok0/java-course-2024-backend 200 0
Molzonas/EkEep 200 3
MrMs1/supple-track-backend 200 0
MyP99999/NewsAggregatorBackend 200 4
Mykindos/BetterPvP 200 15
NIPPORIC/challenge 200 0
NaspoDev/url-shortener 200 2
NastyaLush/java-course-2024-backend 200 3
Ne1loff/OnboardingPlatform 200 3
Neonik-dev/Update-Tracker-Bot 200 7
NevinTure/java-course-2024 200 9
Nick-552/link-tracker 200 7
Nthalk/usafacts-takehome-swapi 200 0
NurtilekMamashakirov/Bot-Link-Tracker 200 2
Nyrheim/PenAndPaper 200 1
OAGi/Score 200 104
Online-Tutoring-Application-Team-11/backend-rest-API-service 200 5
Origin-Masters/Cantine-Planner 200 3
OverLeo007/laba2_ris 200 0
Ovoshchko/BackendTinkoffJavaSpring 200 6
PKNU-CERT-IS/BE 200 60
Pa11ady/java-link-tracker 200 2
Pacan4ik/tinkoff-course-spring2023 200 7
PacktPublishing/-Hands-On-Serverless-with-Kotlin 200 0
ParadiseSS13/TaskDaemon 200 7
PascalHonegger/JassTracker 200 0
PathmindAI/pathmind-webapp 200 32
Penguin-Dream-Team/HDLT 200 0
Penguin-Dream-Team/PenguStore-Server 200 0
PonomarevAlexxander/telegram-notifier 200 4
PresidentChan/indexBot 200 0
Programming-Org/Programming 200 1
Prohkit/java-backend-course-2-link-tracker 200 5
ProstaOlga/prostaBot 200 3
Puru80/food-ordering-system 200 1
QuantuM1o1/Tinkoff2024Homeworks 200 5
RP-Kit/RPKit 200 0
Raha089/oops 200 2
Reazzzz/oosp-zadanya 200 2
Rohan-flutterint/texera 200 2
Rohan-flutterint/tutorials 200 6
RomanZozuliauniversity/Javacourework 200 6
RuslanAndrianov/Backend-Java-Tinkoff-Spring-2024 200 4
RuslanHkmoff/java-backend-course 200 3
SOmegaS/financial-tracker 200 1
Saiyan1/tl-challenge 200 2
SavageSyrop/VK-courses 200 5
ScofieldaCreep/pro-spring-6-kt-chinese-commentation 200 0
ShaDi777/java-course-2024-backend 200 4
ShakurDmitrii/inline 200 2
SightStudio/blog-code 200 15
SleepwalkerPasha/egorov_pa_project 200 3
SlideHehe/java-backend-course-2 200 3
SmallWorlds-Forever/sw-streaming 200 9
SoylentBob/jooq-mock 200 5
Space27/JavaBackendSpring 200 5
Stasik371/LinkTrackingBot 200 4
StubbornJava/StubbornJava 200 4
Stumpwiz/mrradb 200 2
Subtelny/DGCraft 200 20
TaitoUnited/full-stack-template 200 3
TerraByteDev/SkyFactionsReborn 200 17
TheLQ/forum-scraper 200 1
TheShubham-K/getting-started-with-springboot 200 6
Thee5176/SpringBoot_CQRS_Command 200 4
Thee5176/SpringBoot_CQRS_Query 200 6
Thulasidharreddy/task-service 200 1
Tiltuem/tinkoff-java-course-2024 200 6
TivM/Tinkoff-Project 200 5
TomFlag/bookManagement 200 0
Tosin-dotcom/notez-backend 200 4
TovarischZhukov/jooq_example 200 9
TranNgocKhoa/play-framework-java-jooq-example 200 1
TunixR/HarmonyAPI 200 33
UKEIAM/de.uke.iam.parkinson_on_fhir 200 5
UniCodeProjects/AmusementParkDB 200 1
Unite-Organisation/Unite 200 22
VIJAYWHAT/jooq-sample 200 0
VadymOselskyi/airlines-booking 200 8
ViciousXerra/java2024 200 0
VictorGalkevich/LinkScrapper 200 6
ViktoriaGub/Object-oriented-programming-systems 200 2
VladimirMorozov/orm-playground 200 3
VoroninEgor/TgBot-LinkTracker 200 3
Wani4ka/tcs-edu-task 200 4
WolfOfBad/TinkoffJavaCourse2024 200 3
Wovenware/killbill-adyen-plugin 200 0
XinShepherd/spring-boot-jooq-demo 200 0
YAPP-Github/24th-Web-Team-1-BE 200 0
YaroslavChetskiy/tinkoff_course_backend_part 200 8
Yer12/tastamat 200 11
YuliaKrav/WebContentUpdateService 200 3
Yuno-obsessed/jodrive 200 14
Yusuf-s-Islamic-Projetcs/The-Islamic-Discord-Bot 200 0
ZaicevDima/OlympTaskSetter 200 0
ZanottiMatteo/BGTransports 200 11
ZebdaYacine/demofx 200 1
ZenLiuCN/Pandomium-Vue-Spring-template 200 0
ZsgsDesign/openvsx 200 5
ZwierzchowskiM/Client-Server 200 2
aabarmin/telegram-bots 200 3
aahlenst/jOOQ-mcve-json-quoting 200 7
aaiezza/customer-management-api 200 0
aceton41k/java-test-framework 200 3
activej/activej 200 3
aerius/emission-service 200 3
agatha-budget/agatha-budget 200 0
agibalov/java-library-experiments 200 3
aizedevops/spring-boot-projects 200 6
akozitsin-hh/hh-jooq-intro 200 2
aleckbb/tracking-bot 200 3
aleksseii/TradingOperations 200 4
alephzed/baeldung-tutorials 200 6
alex-cova/health 200 0
alexxiuccia/TrackMe 200 9
alipay/container-auto-tune 200 6
allousas/kotlin-sql-libs-comparison 200 0
alpa011235/sandbox 200 1
altusea/wpg 200 1
alvin-qh/study-java 200 10
amalrajvinoth/jooq-optimistic-locking 200 2
anpol84/java-course-2024 200 5
anyamilichenko/soa 200 3
aplygen/j13n-saas 200 3
arhostcode/linktracker 200 3
arijit98/RestaurentManagementService 200 3
arjunbalussery/kotlin-async 200 0
arnaudroger/SimpleFlatMapper 200 11
artemius39/java-backend-2024 200 5
articles-simbirsoft/JOOQ-use-in-testing 200 2
artseroff/link-tracker 200 6
as2network/as2ng 200 0
asm0dey/school-crm 200 0
atolcd/sdis-remocra 200 80
atomfrede/javaland-2022-karate-workshop 200 2
auliardana/Java-orm-jooq 200 2
averbraeck/gamedata-common 200 1
averbraeck/housinggame-common 200 7
averbraeck/trustgame 200 3
averbraeck/trustgame-register 200 2
averbraeck/trustgame-scores 200 2
aws-observability/aws-otel-playground 200 1
aytdm/study 200 2
badgerwithagun/async-all-the-way-down 200 2
balazskrizsan/stackjudge-aws 200 0
balazskrizsan/stackjudge_aws_java 200 2
baudoliver7/payment-base 200 0
beargiles/postgresql-pljava-docker 200 0
beargiles/youtube-dojo 200 1
bennofs/wdumper 200 2
bharat-chaudhari-0302/spring-jooq-gradle-plugin 200 1
bifidok/TinkoffBackend 200 10
bigseized/TinkoffCourseJava2024 200 5
bkamaraj5054/tutorials1 200 6
blueoceandevops/fleet-spring-boot 200 1
boogiespook/waltz-test 200 123
boomzin/dbservice 200 9
bootique-examples/bootique-jooq-examples 200 1
borjom1/cloud-nest 200 13
breandan/typelevel 200 0
brianbcampbell/z_beast-product-catalog 200 1
brianbowden/kotlin-http-server 200 0
brody-0125/Study-Point-Reward-System-Kotlin 200 0
brody-0125/The-Joy-Of-Java 200 2
bsi-software/ScoutJooq 200 38
btpka3/btpka3.github.com 200 3
burst-apps-team/burstpool 200 0
buster/acmemusic 200 4
c00ler/transfer-service 200 4
cardano-foundation/cardano-rosetta-java 200 2
cardano-foundation/cf-ledger-sync 200 0
cashapp/jooq-encryption 200 0
catsloveme/telegram-bot 200 2
cenkakin/meal-planner 200 0
cf-testorg/jOOQ-test 200 76
chaimu100/java-test-for-codeql 200 5
chriswininger/ai-document-query-system 200 3
clearflask/clearflask 200 5
cloudoptlab/cloudopt-next-example 200 0
cn-src/snippets-java 200 4
code-with-dilip/learn-jooq 200 0
codeloopeu/thehub 200 0
coduction/famulex 200 5
comru/spring-jdbc 200 0
constZhur/tinkoff-backend-course-2024 200 4
cooder-org/jooq-mate 200 2
corradomio/java_projects 200 1
coyotesong/spring-boot-with-testcontainers-examples 200 0
craigatk/projektor 200 0
cranes-mentoring/spring-jooq-contest 200 0
crate/cratedb-examples 200 1
crcaguilerapo/data-tier 200 0
crick77/usrbilancio 200 15
crunchykillah/rest_api_springmvc 200 2
curious-odd-man/curious-tunes 200 0
cyberpunkoff/tracktor 200 2
cycastic-cumberland/libmanage-backend 200 5
danmofo/fitness-tracker-app 200 11
darkkeks/telegram-bots 200 0
davinkevin/Podcast-Server 200 0
dbist/cockroach-artifacts 200 0
dbist/cockroach-docker 200 2
dcvetan/bip-backend 200 0
deepakborania/revolut-backend-task 200 2
dehasi/ppp-of-ddd 200 5
derabbink/sws2 200 2
devYSK/study_repo 200 71
devstronomy/nasa-data-scraper 200 1
dgroomes/jooq-playground 200 0
dianainya/platform-backend 200 12
diocorrea/base-kotlin-spring-postgres-template 200 0
diocorrea/imagewrapper 200 1
djma/play-stack 200 1
dmitry-izmerov/revolut-task 200 0
dndanoff/spring-boot-unit-integration-test-example 200 2
docvominh/java 200 0
dominikjaniga91/system-design-interview-projects 200 2
drakejin/carparazzi 200 0
dreamPis/oauth 200 2
drhernandez/gps-api 200 0
duckddud213/Fluffit 200 0
dustinsand/hex-arch-kotlin-spring-boot 200 0
dzorbey/order-scheduling 200 5
easkarov/repo-caretaker 200 3
ebi-gene-expression-group/annotare2 200 1
eclipse-scout/scout.rt 200 11
eclipse/openvsx 200 8
ehrbase/migration-tool 200 18
ekgreen/star-boot 200 7
ekruptsov/jooq-retrofit-crud-poc 200 1
elwin013/todoapp-multitenancy 200 4
emapfff/Link-Tracker 200 6
ennva/java-tutorials-master 200 6
ericdriggs/reportcard 200 3
eterny13/url-shortener 200 1
eugenp/tutorials 200 9
evagalyuta/services-city-discover 200 7
eziomou/library-backend 200 15
f-uni/Quizzy 200 5
fantj2016/springboot-integration 200 1
fasten-project/fasten 200 48
fatihcatalkaya/poker-tracker 200 2
fedemaleh/chess-challenge-java-1 200 3
filipegar/killbill-getnet 200 1
fishedee/Demo 200 9
fuma-nama/U3-Server 200 2
ganigapetaravali/jmeter 200 6
gchq/stroom 200 18
gchq/stroom-auth 200 5
ge1up/healthy-calories_by_spring 200 6
gekoramy/uni.web 200 40
genenakagaki/ddd-sample 200 2
germinateplatform/gatekeeper-server 200 9
gilbertlim/jooq 200 3
giovene44/Cinemanager_Software_Engineering_project 200 8
glassbell/bp-keeper 200 1
glockyco/Teralizer 200 17
gmoon92/toy 200 5
gonzo1138/jOOQinSpring-basics 200 2
gourmetgate/gourmetgate 200 11
graphql-java/graphql-java-db-example 200 1
h8/gradle-jooq-example 200 2
hashgraph/hedera-hcs-erc721-sample 200 10
haumacher/wizard-game 200 1
hevan/agri-cloud 200 30
hiddenswitch/Spellsource 200 1
hieplp/recipe-platform 200 8
hieplp/url-shorten 200 0
hieplp/vinorsoft-hometest 200 4
highloadmipt/expensewriter 200 1
hivtools/hint 200 0
hnstsn/jooq-practice 200 5
hpple/revolut-backend-test 200 5
huruiyi/books-source 200 17
hyt-sasaki/SpringBootMicroServiceTutorial 200 2
iSharkFly-Docs/java-tutorials 200 9
icefery/demo.icefery.xyz 200 1
imi-frankfurt/dataelementhub.dal 200 0
imk0512/book-management-app 200 0
impatient/jooq-types-sample 200 0
innossh/jooq-spring-audit-example 200 0
iotaplatforms/tutorials 200 6
iryazantsev13/rest-jooq-template 200 0
isabella232/bt-dev-prod-data-collector 200 0
itboy87/quarkus-ext-jooq 200 3
iyunbo/stackoverflow 200 1
jOOQ/demo 200 12
jOOQ/jOOQ 200 75
jOOQ/jOOQ-mcve 200 7
jackbergus/java_logicalconsistency 200 6
jasondlee/quarkus-dev-service-full-example 200 3
jasontran320/texera_compose 200 2
java-devil/screen-scream 200 0
jefberpe/restful-demo 200 2
jehugaleahsa/javalin-mvc-starter 200 1
jhavierc/EjemplosJava 200 13
jiangtj-lab/jooq-and-flyway 200 1
jiangtj/jc-platform 200 5
jiangtj/jmicro 200 4
jiftechnify/sbk-jooq 200 0
jihun-ko/spring-boot-coroutine-jooq-example 200 0
jkingster/Tickster 200 2
jklingsporn/quarkus-jooq-reactive-example 200 0
jklingsporn/vertx-jooq 200 4
jmingu/petcrown-backend 200 17
joaoseidel/MussCraft 200 2
joniyed/Super-Java 200 6
joostvdg/cmg-analytics 200 1
jordanamr/Divarena-old 200 1
jsflzhong/cjSpringboot-demo 200 1
juanhaugaard/H2-sakila 200 5
jubicoy/easymapper 200 1
justhecool/SmallWorlds-Forever 200 13
justmasyan/vkhomeworks 200 9
k0patych1/java-course-2023-s2 200 4
k55k32/learn-jooq 200 12
kaeru61/chat_app 200 3
kamarkaka/app-updater 200 3
kamil-sita/labelle 200 31
kanki6315/racing-analysis 200 13
kappsegla/databaseprojects 200 1
kazu-5/kotlin-ddd 200 0
keeleinstituut/ekilex 200 39
kehuka11/graphql_sample 200 4
kenvix/DatabaseWork 200 0
khanactl/mcorpus 200 3
khanhduy-14/pro-todolist-java 200 6
kijko/fed 200 0
killbill/killbill-email-notifications-plugin 200 0
killbill/killbill-stripe-plugin 200 1
kkaravitis/pricing-api 200 2
kmaximk/Link-tracker-bot 200 4
kozakto/ContactManager 200 1
kraczo/craw 200 5
krivonosovti/LinktrackerLast 200 3
krupnoveo/Link-Tracker 200 4
kryakobess/TinkoffBackendCourse 200 2
ksamorodov/SpringAuth 200 1
ksamorodov/corset 200 1
kushtrimh/tomorr 200 7
kuvasz-uptime/kuvasz 200 0
kyhyeok/jOOQ 200 11
kyoneken/book-manager 200 0
labinochka/semester-work-agona 200 2
lahraye/farm-collector-task 200 1
lamarios/mmath 200 1
lebenasa-tvlk/plutus-bootcamp 200 0
lelup24/blog 200 2
lelup24/spring-boot-websocket 200 1
leoiii12/csci3170-project 200 4
leoleelwl/springboot_jooq_flyway 200 1
lesam19092/Tinkoff_first_project 200 2
letPeace/VK-homework-6 200 3
lightningdevkit/vss-server 200 3
liljarn/tinkoffCourseJava2024 200 3
lin-mt/spring-boot 200 1
linux-china/jooq-demo 200 4
liuyueyi/spring-boot-demo 200 7
liuzheming/merchant-feecal-mvp 200 8
ljk0071/side-project-back 200 12
ljseo/Fluffit 200 0
lmyslinski/prhunter-api 200 0
lsfoster64/gymhelper 200 1
lsn03/java-2023-backend-second-semester 200 6
luchshiyDed/JavaTasks 200 0
lwbeamer/tinkoff-course 200 4
lzbkln/java-course-tinkoff-spring-2024 200 9
lzj09/sw-jooq 200 1
mackokodzi/analytics-warehouse 200 0
magicswissweed/MagicSwissWeed2.0 200 10
makeitfine-org/mif 200 3
maksmolchdmitr/tinkoffLinkUpdater 200 3
mangilimatteo/Progetto_Ingegneria_Software_Cattaneo_Mangili_Saini 200 0
marcato10/manaca-framework 200 1
marcelocordeiro/spring-basics 200 0
marijarin/tin_back_hws 200 2
marlind89/kensa 200 4
martynovvladislav/tinkoff-java-backend-course-2024 200 3
matco/hotspot-api 200 10
matuolis/financial-analysis-be 200 7
matuolis/vehicle-marketplace-be 200 8
maulanauls/spring-exam 200 0
maximister/LinkTrackerBot 200 3
mbto/eatlog 200 10
mbto/funnyranks 200 17
mehdikeshani/MyFasten 200 49
menosbel/UrlShortner 200 0
merlimmateus/vidsummize 200 1
metaloom/loom 200 28
metaloom/poc-vertx-jooq 200 0
migibert/embro 200 5
miguelperezcolom/mateu-article-2 200 13
mikerasch/dal 200 1
mingtiangg/LTG 200 17
mini-crm/mini-crm 200 8
miqqra/TinkoffBackendCourse 200 0
mistresssfilth/HM8 200 2
miyahira0902/bookManager 200 0
mizumura3/tech6-spring-kotlin-jooq 200 0
mochegov/rock-paper-scissors 200 4
modlix-india/nocode-saas 200 10
morning-code/db 200 0
mrc-ide/auth-api 200 0
mullerhai/mysql-modeldb 200 60
murl-digital/squier 200 2
mwilkins91/mythology-v2 200 2
my1exp/YC_Pay 200 3
mytakedotorg/mtdo 200 21
mzdluo123/TimeTableBot 200 0
nameishari/money-transfer-service 200 4
navikt/veilarblest 200 3
neekon2508/SpringStudy 200 4
neptunejing/SkillUp-Ecom-Plat 200 8
nianien/jooq-tutorial 200 4
nianien/katana 200 3
nice1111hh/Java2 200 6
nicolaj0/smino 200 6
nicolaslecrique/guessit 200 0
nikguscode/HackathonMax 200 6
nikolay-klekto/FunScrutContactCenterBot 200 10
niranjankhare/SeleniumPageModeller 200 2
njuro/FarmAssignment 200 0
nocarend/Tinkoff-Edu-Backend-Java 200 3
noir2k/speechear 200 5
nortal/GovStack-IM-BB-PubSub-Component 200 15
northcoder-repo/jooqSakilaDemo 200 3
nsn/jooqmve 200 0
nuromirzak/tinkoff_academy 200 4
nyh1030/rocketmart-pcweb 200 6
ojhughes/concourse-http-lock-resource 200 2
okosatka/usermanagement 200 0
oneops/oneops 200 1
optimus-alfaomega/Java-Casos-Practicos 200 7
oracle/graalvm-reachability-metadata 200 2
otto15/ITMO-WEB-LAB3 200 1
owengrant/spooch 200 0
pawelWielkolinski/SDABetApp 200 6
pedroafonsodias/springboot 200 2
pedroermarinho/teach-sync 200 3
philosopherstonerush/java-notes 200 1
phpbae/JOOQ 200 2
picodotdev/blog-ejemplos 200 13
pivotal-mark-higuera/tutorials 200 5
pnci1029/mypro 200 1
poemp/metadata-gather 200 5
polytech-attendance/taskbot 200 4
ppretki/mysql-spatial-data 200 1
pratyush05/trade-app 200 3
pro100bat9/tg_chat 200 4
propan/tea-buddy 200 4
prskr/SA-Jericho 200 0
puzink/Wallet 200 2

In [10]:
print(df['response_code2'].value_counts())
print(df['result_count2'].value_counts())
df

response_code2
200    802
Name: count, dtype: int64
result_count2
0      157
1      122
2       99
3       86
4       70
5       53
6       45
7       26
8       20
9       15
11      13
10      12
12      11
15      10
13       8
17       7
18       3
14       3
80       2
16       2
26       2
39       2
30       2
24       2
60       2
32       2
38       2
48       2
37       1
41       1
22       1
104      1
19       1
23       1
123      1
20       1
33       1
76       1
40       1
75       1
31       1
71       1
49       1
28       1
50       1
21       1
66       1
78       1
27       1
29       1
Name: count, dtype: int64

,name,response_code,result_count,response_code2,result_count2
0,2023-ict-itmo-city-project/city-project-backen...,200,1,200,0
1,320Hwany/jOOQ-Study,200,1,200,0
2,4el1k/Spring-Api-Hibernate-JOOQ,200,1,200,5
3,51568488/vertx-zero,200,1,200,1
4,66xc1/lazy-punch,200,1,200,5
...,...,...,...,...,...
797,zhuyb0614/graph-batis,200,1,200,6
798,zigzag191/java-backend-course-2024,200,1,200,3
799,zjxkenshine/codedemo,200,1,200,1
800,zodac-personal/folding-stats,200,1,200,1
801,zubairmujeeb/spring-boot-sample-projects,200,1,200,6

In [11]:
df_valid = df[df['result_count2'] > 0]
df_valid

,name,response_code,result_count,response_code2,result_count2
2,4el1k/Spring-Api-Hibernate-JOOQ,200,1,200,5
3,51568488/vertx-zero,200,1,200,1
4,66xc1/lazy-punch,200,1,200,5
5,ABCLV/ABLV_IngSW,200,1,200,1
6,APSfurizon/fz-backend,200,1,200,3
...,...,...,...,...,...
797,zhuyb0614/graph-batis,200,1,200,6
798,zigzag191/java-backend-course-2024,200,1,200,3
799,zjxkenshine/codedemo,200,1,200,1
800,zodac-personal/folding-stats,200,1,200,1
801,zubairmujeeb/spring-boot-sample-projects,200,1,200,6

In [12]:
df_valid.to_csv('../datasets/repositories-with-java-source-files.csv', index=False)