In [1]:
import pandas as pd

In [2]:
ground_truth_df = pd.read_csv('../datasets/ground-truth.csv')
ground_truth_df

,Project,Antipattern,File,Line from,Line to,Comment
0,alexxiuccia/TrackMe,Rounding Errors,codice/TM_db/src-generated/it/trackme/jooq/gen...,71,71,toiteväärtuse andmed
1,alexxiuccia/TrackMe,Rounding Errors,codice/TM_db/src-generated/it/trackme/jooq/gen...,76,76,toiteväärtuse andmed
2,alexxiuccia/TrackMe,Rounding Errors,codice/TM_db/src-generated/it/trackme/jooq/gen...,81,81,toiteväärtuse andmed
3,alexxiuccia/TrackMe,Keyless Entry,codice/TM_db/src-generated/it/trackme/jooq/gen...,55,55,viide ricetta tabeli primaarvõtmele
4,alexxiuccia/TrackMe,Keyless Entry,codice/TM_db/src-generated/it/trackme/jooq/gen...,60,60,viide alimento tabeli primaarvõtmele
...,...,...,...,...,...,...
1557,ydeng11/Minance,Implicit Columns,src/main/java/today/ihelio/minance/service/Ban...,61,61,select(TABLE).from(TABLE)
1558,ydeng11/Minance,Implicit Columns,src/main/java/today/ihelio/minance/service/Cat...,115,115,selectDistinct(TABLE).from(TABLE)
1559,ydeng11/Minance,Implicit Columns,src/main/java/today/ihelio/minance/service/Tra...,98,98,select(TABLE).from(TABLE)
1560,ydeng11/Minance,Implicit Columns,src/main/java/today/ihelio/minance/service/Tra...,105,105,select(TABLE).from(TABLE)
1561,ydeng11/Minance,Implicit Columns,src/main/java/today/ihelio/minance/service/Tra...,113,113,select(TABLE).from(TABLE)

In [3]:
# Each project contained at least one antipattern so this is valid
total_project_count = ground_truth_df["Project"].unique().size
total_project_count

61

In [4]:
result_df = pd.DataFrame(ground_truth_df["Antipattern"].unique(), columns=["Antipattern"])
result_df = result_df.assign(
    **{
        "Instance count": 0,
        "Containing project count": 0, 
        "Instances per any project": 0.0, 
        "Instances per containing project": 0.0
    }
)
result_df

,Antipattern,Instance count,Containing project count,Instances per any project,Instances per containing project
0,Rounding Errors,0,0,0.0,0.0
1,Keyless Entry,0,0,0.0,0.0
2,31 Flavors,0,0,0.0,0.0
3,Implicit Columns,0,0,0.0,0.0
4,Readable Passwords,0,0,0.0,0.0
5,ID Required,0,0,0.0,0.0
6,Naive Trees,0,0,0.0,0.0
7,Beware of the Unknown,0,0,0.0,0.0
8,Poor Man’s Search Engine,0,0,0.0,0.0
9,Phantom Files,0,0,0.0,0.0
10,Polymorphic Associations,0,0,0.0,0.0
11,Jaywalking,0,0,0.0,0.0
12,Metadata Tribbles,0,0,0.0,0.0
13,Entity-Attribute-Value,0,0,0.0,0.0
14,SQL Injection,0,0,0.0,0.0
15,Ambiguous Groups,0,0,0.0,0.0
16,Standard Operating Procedures,0,0,0.0,0.0
17,Random Selection,0,0,0.0,0.0
18,Multicolumn Attributes,0,0,0.0,0.0

In [5]:
# Number of total occurrences
for index, row in result_df.iterrows():
    count = ground_truth_df[ground_truth_df["Antipattern"] == row["Antipattern"]].shape[0]
    result_df.loc[index, "Instance count"] = count

In [6]:
# Number of antipatterns instances per project (including projects that do not contain the antipattern)
for index, row in result_df.iterrows():
    count = ground_truth_df[ground_truth_df["Antipattern"] == row["Antipattern"]].shape[0] / total_project_count
    result_df.loc[index, "Instances per any project"] = count

In [7]:
# Number of projects containing each antipattern
for index, row in result_df.iterrows():
    count = ground_truth_df[ground_truth_df["Antipattern"] == row["Antipattern"]]["Project"].unique().size
    result_df.loc[index, "Containing project count"] = count

In [8]:
# Number of antipatterns instances per project (only including projects that contain the antipattern)
for index, row in result_df.iterrows():
    df_antipattern = ground_truth_df[ground_truth_df["Antipattern"] == row["Antipattern"]]
    project_count = df_antipattern["Project"].unique().size
    result_df.loc[index, "Instances per containing project"] = df_antipattern.shape[0] / project_count

In [9]:
result_df.sort_values(by=["Instance count", "Containing project count"], ascending=False, ignore_index=True)

,Antipattern,Instance count,Containing project count,Instances per any project,Instances per containing project
0,Implicit Columns,795,59,13.032787,13.474576
1,ID Required,259,49,4.245902,5.285714
2,Keyless Entry,122,11,2.000000,11.090909
3,Beware of the Unknown,95,19,1.557377,5.000000
4,31 Flavors,71,11,1.163934,6.454545
5,Poor Man’s Search Engine,55,12,0.901639,4.583333
6,Polymorphic Associations,40,1,0.655738,40.000000
7,Rounding Errors,39,7,0.639344,5.571429
8,Ambiguous Groups,24,2,0.393443,12.000000
9,Readable Passwords,14,9,0.229508,1.555556
10,Phantom Files,10,8,0.163934,1.250000
11,Naive Trees,10,4,0.163934,2.500000
12,Standard Operating Procedures,8,1,0.131148,8.000000
13,Jaywalking,6,2,0.098361,3.000000
14,Metadata Tribbles,5,3,0.081967,1.666667
15,Entity-Attribute-Value,3,3,0.049180,1.000000
16,SQL Injection,3,1,0.049180,3.000000
17,Random Selection,2,1,0.032787,2.000000
18,Multicolumn Attributes,1,1,0.016393,1.000000

In [10]:
included_antipatterns_df = result_df[result_df["Instance count"] > 25]
included_antipatterns_df = included_antipatterns_df[included_antipatterns_df["Containing project count"] > 3]
included_antipatterns_df.sort_values(by=["Instance count", "Containing project count"], ascending=False, ignore_index=True)

,Antipattern,Instance count,Containing project count,Instances per any project,Instances per containing project
0,Implicit Columns,795,59,13.032787,13.474576
1,ID Required,259,49,4.245902,5.285714
2,Keyless Entry,122,11,2.000000,11.090909
3,Beware of the Unknown,95,19,1.557377,5.000000
4,31 Flavors,71,11,1.163934,6.454545
5,Poor Man’s Search Engine,55,12,0.901639,4.583333
6,Rounding Errors,39,7,0.639344,5.571429